language: cpp
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -DENABLE_COVERAGE=ON -DUTL_NO_EXCEPTIONS=OFF .
  - cmake --build . -- -j2
  - ctest -j2
  - lcov --gcov-tool /usr/bin/gcov-7 --directory . --capture --output-file coverage.info
  - lcov --gcov-tool /usr/bin/gcov-7 -remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --gcov-tool /usr/bin/gcov-7 -remove coverage.info '*/doctest.h' --output-file coverage.info
  - lcov --gcov-tool /usr/bin/gcov-7 -list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
